//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nordfin.AutoAccount {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://webservice.creditsafe.se", ConfigurationName="AutoAccount.AutoAccountServiceSoap")]
    public interface AutoAccountServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestXmlStr from namespace https://webservice.creditsafe.se is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.creditsafe.se/AutoAccount", ReplyAction="*")]
        Nordfin.AutoAccount.AutoAccountResponse AutoAccount(Nordfin.AutoAccount.AutoAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.creditsafe.se/AutoAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<Nordfin.AutoAccount.AutoAccountResponse> AutoAccountAsync(Nordfin.AutoAccount.AutoAccountRequest request);
        
        // CODEGEN: Generating message contract since element name requestXmlStr from namespace https://webservice.creditsafe.se is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.creditsafe.se/GetPackageList", ReplyAction="*")]
        Nordfin.AutoAccount.GetPackageListResponse GetPackageList(Nordfin.AutoAccount.GetPackageListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.creditsafe.se/GetPackageList", ReplyAction="*")]
        System.Threading.Tasks.Task<Nordfin.AutoAccount.GetPackageListResponse> GetPackageListAsync(Nordfin.AutoAccount.GetPackageListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoAccount", Namespace="https://webservice.creditsafe.se", Order=0)]
        public Nordfin.AutoAccount.AutoAccountRequestBody Body;
        
        public AutoAccountRequest() {
        }
        
        public AutoAccountRequest(Nordfin.AutoAccount.AutoAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.creditsafe.se")]
    public partial class AutoAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXmlStr;
        
        public AutoAccountRequestBody() {
        }
        
        public AutoAccountRequestBody(string requestXmlStr) {
            this.requestXmlStr = requestXmlStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoAccountResponse", Namespace="https://webservice.creditsafe.se", Order=0)]
        public Nordfin.AutoAccount.AutoAccountResponseBody Body;
        
        public AutoAccountResponse() {
        }
        
        public AutoAccountResponse(Nordfin.AutoAccount.AutoAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.creditsafe.se")]
    public partial class AutoAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoAccountResult;
        
        public AutoAccountResponseBody() {
        }
        
        public AutoAccountResponseBody(string AutoAccountResult) {
            this.AutoAccountResult = AutoAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPackageListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPackageList", Namespace="https://webservice.creditsafe.se", Order=0)]
        public Nordfin.AutoAccount.GetPackageListRequestBody Body;
        
        public GetPackageListRequest() {
        }
        
        public GetPackageListRequest(Nordfin.AutoAccount.GetPackageListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.creditsafe.se")]
    public partial class GetPackageListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXmlStr;
        
        public GetPackageListRequestBody() {
        }
        
        public GetPackageListRequestBody(string requestXmlStr) {
            this.requestXmlStr = requestXmlStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPackageListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPackageListResponse", Namespace="https://webservice.creditsafe.se", Order=0)]
        public Nordfin.AutoAccount.GetPackageListResponseBody Body;
        
        public GetPackageListResponse() {
        }
        
        public GetPackageListResponse(Nordfin.AutoAccount.GetPackageListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.creditsafe.se")]
    public partial class GetPackageListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPackageListResult;
        
        public GetPackageListResponseBody() {
        }
        
        public GetPackageListResponseBody(string GetPackageListResult) {
            this.GetPackageListResult = GetPackageListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutoAccountServiceSoapChannel : Nordfin.AutoAccount.AutoAccountServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoAccountServiceSoapClient : System.ServiceModel.ClientBase<Nordfin.AutoAccount.AutoAccountServiceSoap>, Nordfin.AutoAccount.AutoAccountServiceSoap {
        
        public AutoAccountServiceSoapClient() {
        }
        
        public AutoAccountServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoAccountServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoAccountServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoAccountServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nordfin.AutoAccount.AutoAccountResponse Nordfin.AutoAccount.AutoAccountServiceSoap.AutoAccount(Nordfin.AutoAccount.AutoAccountRequest request) {
            return base.Channel.AutoAccount(request);
        }
        
        public string AutoAccount(string requestXmlStr) {
            Nordfin.AutoAccount.AutoAccountRequest inValue = new Nordfin.AutoAccount.AutoAccountRequest();
            inValue.Body = new Nordfin.AutoAccount.AutoAccountRequestBody();
            inValue.Body.requestXmlStr = requestXmlStr;
            Nordfin.AutoAccount.AutoAccountResponse retVal = ((Nordfin.AutoAccount.AutoAccountServiceSoap)(this)).AutoAccount(inValue);
            return retVal.Body.AutoAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nordfin.AutoAccount.AutoAccountResponse> Nordfin.AutoAccount.AutoAccountServiceSoap.AutoAccountAsync(Nordfin.AutoAccount.AutoAccountRequest request) {
            return base.Channel.AutoAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nordfin.AutoAccount.AutoAccountResponse> AutoAccountAsync(string requestXmlStr) {
            Nordfin.AutoAccount.AutoAccountRequest inValue = new Nordfin.AutoAccount.AutoAccountRequest();
            inValue.Body = new Nordfin.AutoAccount.AutoAccountRequestBody();
            inValue.Body.requestXmlStr = requestXmlStr;
            return ((Nordfin.AutoAccount.AutoAccountServiceSoap)(this)).AutoAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nordfin.AutoAccount.GetPackageListResponse Nordfin.AutoAccount.AutoAccountServiceSoap.GetPackageList(Nordfin.AutoAccount.GetPackageListRequest request) {
            return base.Channel.GetPackageList(request);
        }
        
        public string GetPackageList(string requestXmlStr) {
            Nordfin.AutoAccount.GetPackageListRequest inValue = new Nordfin.AutoAccount.GetPackageListRequest();
            inValue.Body = new Nordfin.AutoAccount.GetPackageListRequestBody();
            inValue.Body.requestXmlStr = requestXmlStr;
            Nordfin.AutoAccount.GetPackageListResponse retVal = ((Nordfin.AutoAccount.AutoAccountServiceSoap)(this)).GetPackageList(inValue);
            return retVal.Body.GetPackageListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nordfin.AutoAccount.GetPackageListResponse> Nordfin.AutoAccount.AutoAccountServiceSoap.GetPackageListAsync(Nordfin.AutoAccount.GetPackageListRequest request) {
            return base.Channel.GetPackageListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nordfin.AutoAccount.GetPackageListResponse> GetPackageListAsync(string requestXmlStr) {
            Nordfin.AutoAccount.GetPackageListRequest inValue = new Nordfin.AutoAccount.GetPackageListRequest();
            inValue.Body = new Nordfin.AutoAccount.GetPackageListRequestBody();
            inValue.Body.requestXmlStr = requestXmlStr;
            return ((Nordfin.AutoAccount.AutoAccountServiceSoap)(this)).GetPackageListAsync(inValue);
        }
    }
}
